#!/usr/bin/env bash
# Print a fingerprint of the APP SOURCES the release notes describe.
#
# Why a stored fingerprint and not `git log <last-tag>..HEAD`: CI checks out shallow (no
# `fetch-depth: 0`, no tags), so a history-based check would either error or silently pass
# — the worst kind of gate. A hash committed beside the notes travels with the tree and
# answers the only question that matters: has the app changed since anyone last wrote a
# user-facing line about it?
#
# EXCLUDED, and why each one has to be:
#   · version.ts / releaseNotes.ts — generated BY the stamp; including them would make the
#     fingerprint change as a side effect of recording it.
#   · tests — a test-only change is real work and zero user-visible change; counting it
#     would demand a release note for a refactor nobody can see.
#
# BOUNDARY, stated rather than hidden: this watches `mobileapp/src` only. A change confined
# to the native iOS targets (widget, notification service) is user-visible and would NOT be
# caught. That is a deliberate simplification — every miss this gate was written for
# (#738, #739, #744) lived in `src` — not a claim that `src` is the whole app.
set -euo pipefail

cd "$(dirname "$0")/.."

find src -type f \
  ! -name version.ts \
  ! -name releaseNotes.ts \
  ! -name '*.test.ts' \
  ! -name '*.test.tsx' \
  ! -path '*/__tests__/*' \
  -print0 |
  LC_ALL=C sort -z |
  xargs -0 shasum -a 256 |
  shasum -a 256 |
  cut -d' ' -f1
