#!/usr/bin/env bash
# Emit mobileapp/src/releaseNotes.ts to STDOUT, generated from the per-version archive in
# mobileapp/release-notes/ (see the README there).
#
# The in-app "What's New" popup renders these. It has to answer a harder question than the
# App Store listing does — a user who skipped three versions must see all three — so the
# archive, not the (per-release overwritten) store metadata, is the source, and every
# shipped version's notes ride in the binary.
#
# Writing to stdout (rather than to the file) is what lets the conformance gate check for
# drift by DIFFING this output against the committed file: "would regenerating change
# anything?" is a byte-exact question, with none of the un-escaping guesswork that comparing
# a TS string literal back to its source would need.
#
# Called by set-version.sh (which redirects it into place) and by scripts/check-design.sh.
set -euo pipefail

cd "$(dirname "$0")/.."

# Newest version first, the order the popup reads in. `sort -V` puts 0.9 before 0.10, which
# a lexical sort would get backwards the first time a minor hits double digits.
versions() {
  ls release-notes/*.en.txt 2>/dev/null |
    sed -e 's|release-notes/||' -e 's|\.en\.txt$||' |
    sort -Vr
}

emit() {  # $1 = file of bullets
  [ -f "$1" ] || return 0
  # One bullet per line: strip a leading "• ", drop blank lines, and escape backslash and
  # the single quote so the text is safe inside a TS single-quoted string — the notes are
  # prose written by a human and WILL eventually contain an apostrophe.
  awk '
    { sub(/^[[:space:]]*•[[:space:]]*/, ""); sub(/[[:space:]]+$/, "") }
    /^$/ { next }
    { gsub(/\\/, "\\\\"); gsub(/\x27/, "\\\x27"); printf "      \x27%s\x27,\n", $0 }
  ' "$1"
}

cat <<'HEADER'
// Generated by scripts/gen-release-notes.sh from mobileapp/release-notes/ — do not edit by
// hand. One entry per shipped version, NEWEST FIRST, so a user who skipped versions sees
// every one they crossed. scripts/check-design.sh fails when this file and the archive
// disagree; re-run mobileapp/scripts/set-version.sh to fix.

/** One shipped version's user-facing notes, in both languages. */
export interface ReleaseNote {
  version: string;
  en: string[];
  zh: string[];
}

export const RELEASE_NOTES: ReleaseNote[] = [
HEADER
for v in $(versions); do
  echo "  {"
  echo "    version: '$v',"
  echo "    en: ["
  emit "release-notes/$v.en.txt"
  echo "    ],"
  echo "    zh: ["
  emit "release-notes/$v.zh.txt"
  echo "    ],"
  echo "  },"
done
echo "];"
