#!/usr/bin/env bash
# Sync the mobile app version to the latest gtmux release tag, so the in-app
# Settings version (and the native CFBundleShortVersionString, when the build
# passes MARKETING_VERSION) reflect the actual release instead of a stale 0.0.1.
#
# Run before building:  mobileapp/scripts/set-version.sh
# Then it prints the version; pass it to xcodebuild as MARKETING_VERSION.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

VER="$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')"
[ -n "$VER" ] || VER="0.0.0"

OUT="mobileapp/src/version.ts"
cat > "$OUT" <<EOF
// Generated by scripts/set-version.sh from the latest git tag — do not edit by
// hand. Committed so a fresh checkout builds; the device-build regenerates it.
export const APP_VERSION = '$VER';
EOF

# Also sync the native MARKETING_VERSION in the pbxproj, so a store ARCHIVE (which
# reads MARKETING_VERSION from the project, NOT from a MARKETING_VERSION= xcarg) ships
# the same version. Without this the two drift: version.ts said 0.41.0 while the pbxproj
# sat at a stale 1.0, and the fastlane release/metadata lanes read the pbxproj — so the
# App Store version would have been 1.0. All targets (app + widget + notif-service) share
# one app version.
PBX="mobileapp/ios/GtmuxMobile.xcodeproj/project.pbxproj"
if [ -f "$PBX" ]; then
  sed -i '' "s/MARKETING_VERSION = [0-9][0-9.]*;/MARKETING_VERSION = ${VER};/g" "$PBX"
fi

echo "$VER"
