#!/usr/bin/env bash
# Sync the mobile app version to the latest gtmux release tag, so the in-app
# Settings version (and the native CFBundleShortVersionString, when the build
# passes MARKETING_VERSION) reflect the actual release instead of a stale 0.0.1.
#
# Run before building:  mobileapp/scripts/set-version.sh
# Then it prints the version; pass it to xcodebuild as MARKETING_VERSION.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

VER="$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')"
[ -n "$VER" ] || VER="0.0.0"

OUT="mobileapp/src/version.ts"
cat > "$OUT" <<EOF
// Generated by scripts/set-version.sh from the latest git tag — do not edit by
// hand. Committed so a fresh checkout builds; the device-build regenerates it.
export const APP_VERSION = '$VER';
EOF

# Also sync the native MARKETING_VERSION in the pbxproj, so a store ARCHIVE (which
# reads MARKETING_VERSION from the project, NOT from a MARKETING_VERSION= xcarg) ships
# the same version. Without this the two drift: version.ts said 0.41.0 while the pbxproj
# sat at a stale 1.0, and the fastlane release/metadata lanes read the pbxproj — so the
# App Store version would have been 1.0. All targets (app + widget + notif-service) share
# one app version.
PBX="mobileapp/ios/GtmuxMobile.xcodeproj/project.pbxproj"
if [ -f "$PBX" ]; then
  sed -i '' "s/MARKETING_VERSION = [0-9][0-9.]*;/MARKETING_VERSION = ${VER};/g" "$PBX"
fi

# ── in-app What's New ────────────────────────────────────────────────────────
# ARCHIVE this version's store notes, then regenerate the bundled history.
#
# The App Store metadata holds only the CURRENT submission's notes (fastlane overwrites it
# every release), but the in-app popup must show a user who skipped three versions all
# three — so each stamped version's notes are copied into release-notes/ and the whole
# archive is compiled into src/releaseNotes.ts. The normal release flow needs no extra
# step: write the store notes as always, stamp the version, and the archive grows.
#
# Archived ONLY when the notes actually changed. The app version follows the gtmux git
# tag, so most stamps cross a version the mobile app never shipped (a CLI-only release) —
# copying the notes under each of those would show the reader the SAME bullets under two
# version headings, which is worse than saying nothing. Comparing against the newest
# archived entry keeps the history to versions that really said something new, and keeps
# the flow free of a step anyone has to remember.
mkdir -p mobileapp/release-notes
prev="$(ls mobileapp/release-notes/*.en.txt 2>/dev/null | sed -e 's|.*/||' -e 's|\.en\.txt$||' | sort -Vr | head -1)"
changed=0
for pair in "en-US:en" "zh-Hans:zh"; do
  src="mobileapp/fastlane/metadata/${pair%%:*}/release_notes.txt"
  [ -f "$src" ] || continue
  old="mobileapp/release-notes/${prev}.${pair##*:}.txt"
  if [ -z "$prev" ] || [ ! -f "$old" ] || ! cmp -s "$src" "$old"; then changed=1; fi
done
if [ "$changed" = 1 ]; then
  for pair in "en-US:en" "zh-Hans:zh"; do
    src="mobileapp/fastlane/metadata/${pair%%:*}/release_notes.txt"
    [ -f "$src" ] && cp "$src" "mobileapp/release-notes/${VER}.${pair##*:}.txt"
  done
fi
bash mobileapp/scripts/gen-release-notes.sh > mobileapp/src/releaseNotes.ts

echo "$VER"
