#!/usr/bin/env bash
# Sync the mobile app version to the latest gtmux release tag, so the in-app
# Settings version (and the native CFBundleShortVersionString, when the build
# passes MARKETING_VERSION) reflect the actual release instead of a stale 0.0.1.
#
# Run before building:  mobileapp/scripts/set-version.sh
# Then it prints the version; pass it to xcodebuild as MARKETING_VERSION.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

VER="$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')"
[ -n "$VER" ] || VER="0.0.0"

OUT="mobileapp/src/version.ts"
cat > "$OUT" <<EOF
// Generated by scripts/set-version.sh from the latest git tag — do not edit by
// hand. Committed so a fresh checkout builds; the device-build regenerates it.
export const APP_VERSION = '$VER';
EOF

echo "$VER"
