package transcript

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
)

// Claude Code logs live at ~/.claude/projects/<cwd-slug>/<sessionId>.jsonl, one
// JSON event per line. We glob by sessionId so we never reconstruct the cwd-slug
// encoding. Each line has a top-level `type`; the conversation is reconstructed
// linearly (a full parentUuid DAG is overkill for a recent-history glance):
//   user prompt → assistant text/tool_use* … → final assistant text.
//
// Schema notes (from the 2026-06 prior-art survey, see docs/design/RESEARCH-…):
//   - message.content is `string | block[]`; user prompts are often a bare string.
//   - tool results come back as `user` events whose content is tool_result blocks
//     — those are NOT new prompts, so they don't open a turn.
//   - the FINAL assistant message has stop_reason=="end_turn" (tool_use is mid-turn);
//     we approximate by letting the latest assistant text win.
//   - isMeta (slash-command echo) and isSidechain (sub-agent) entries are skipped
//     so they don't pollute the main timeline.
//   - unknown `type` values (ai-title/queue-operation/attachment/…) are ignored.

type claudeLine struct {
	Type        string         `json:"type"`
	IsMeta      bool           `json:"isMeta"`
	IsSidechain bool           `json:"isSidechain"`
	Message     *claudeMessage `json:"message"`
}

type claudeMessage struct {
	Role       string          `json:"role"`
	Content    json.RawMessage `json:"content"`
	StopReason string          `json:"stop_reason"`
}

type claudeBlock struct {
	Type  string          `json:"type"`
	Text  string          `json:"text"`
	Name  string          `json:"name"`
	Input json.RawMessage `json:"input"`
}

func claudeLogPath(sessionID string) string {
	matches, _ := filepath.Glob(filepath.Join(claudeProjectsDir(), "*", sessionID+".jsonl"))
	if len(matches) > 0 {
		return matches[0]
	}
	return ""
}

func claudeProjectsDir() string {
	return filepath.Join(os.Getenv("HOME"), ".claude", "projects")
}

func loadClaude(sessionID string, maxTurns int) ([]Turn, error) {
	path := claudeLogPath(sessionID)
	if path == "" {
		return nil, nil
	}
	lines, err := tailLines(path)
	if err != nil {
		return nil, err
	}

	var turns []Turn
	var cur *Turn
	flush := func() {
		if cur != nil && (cur.Prompt != "" || cur.Response != "" || len(cur.Steps) > 0) {
			turns = append(turns, *cur)
		}
		cur = nil
	}

	for _, line := range lines {
		var e claudeLine
		if json.Unmarshal([]byte(line), &e) != nil || e.Message == nil || e.IsSidechain {
			continue
		}
		switch e.Type {
		case "user":
			if e.IsMeta {
				continue
			}
			prompt, isPrompt := claudePrompt(e.Message.Content)
			if !isPrompt {
				continue // a tool_result-only user event — not a new turn
			}
			flush()
			cur = &Turn{Prompt: prompt}
		case "assistant":
			if cur == nil {
				cur = &Turn{} // tail started mid-turn (no preceding prompt)
			}
			text, steps := claudeAssistant(e.Message.Content)
			if text != "" {
				cur.Response = text // latest assistant text wins → the final reply
			}
			cur.Steps = append(cur.Steps, steps...)
		}
	}
	flush()
	return lastN(turns, maxTurns), nil
}

// claudePrompt extracts a user-typed prompt from message.content. Returns ok=false
// when the content is a tool result (not a real prompt) or empty/meta wrapper.
func claudePrompt(raw json.RawMessage) (string, bool) {
	if len(raw) == 0 {
		return "", false
	}
	// content as a bare string (the common typed-prompt case).
	var s string
	if json.Unmarshal(raw, &s) == nil {
		s = strings.TrimSpace(s)
		if s == "" || isClaudeMetaPrompt(s) {
			return "", false
		}
		return s, true
	}
	// content as blocks: collect text, ignore tool_result-only payloads.
	var blocks []claudeBlock
	if json.Unmarshal(raw, &blocks) != nil {
		return "", false
	}
	var parts []string
	for _, b := range blocks {
		if b.Type == "text" && strings.TrimSpace(b.Text) != "" {
			parts = append(parts, strings.TrimSpace(b.Text))
		}
	}
	if len(parts) == 0 {
		return "", false // tool_result / image only
	}
	s = strings.TrimSpace(strings.Join(parts, "\n"))
	if s == "" || isClaudeMetaPrompt(s) {
		return "", false
	}
	return s, true
}

// isClaudeMetaPrompt filters the synthetic wrappers Claude injects as "user"
// content (slash-command echoes, local-command stdout, the local-command caveat).
func isClaudeMetaPrompt(s string) bool {
	return strings.HasPrefix(s, "<command-") ||
		strings.HasPrefix(s, "<local-command-") ||
		strings.HasPrefix(s, "Caveat: The messages below were generated by the user while running local commands")
}

// claudeAssistant returns the concatenated text of an assistant message and its
// tool_use blocks as Steps.
func claudeAssistant(raw json.RawMessage) (string, []Step) {
	var blocks []claudeBlock
	if json.Unmarshal(raw, &blocks) != nil {
		// some assistant messages carry a bare string
		var s string
		if json.Unmarshal(raw, &s) == nil {
			return strings.TrimSpace(s), nil
		}
		return "", nil
	}
	var text []string
	var steps []Step
	for _, b := range blocks {
		switch b.Type {
		case "text":
			if strings.TrimSpace(b.Text) != "" {
				text = append(text, strings.TrimSpace(b.Text))
			}
		case "tool_use":
			steps = append(steps, Step{Kind: "tool", Title: b.Name, Detail: toolDetail(b.Input)})
		}
	}
	return strings.TrimSpace(strings.Join(text, "\n")), steps
}

// toolDetail picks a short, human-meaningful summary from a tool_use input object
// (file path / command / pattern / url …).
func toolDetail(input json.RawMessage) string {
	if len(input) == 0 {
		return ""
	}
	var m map[string]any
	if json.Unmarshal(input, &m) != nil {
		return ""
	}
	for _, k := range []string{"file_path", "path", "command", "pattern", "url", "query", "description", "prompt"} {
		if v, ok := m[k]; ok {
			if s, ok := v.(string); ok && strings.TrimSpace(s) != "" {
				return clip(s, 80)
			}
		}
	}
	return ""
}
