package transcript

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Claude Code logs live at ~/.claude/projects/<cwd-slug>/<sessionId>.jsonl, one
// JSON event per line. We glob by sessionId so we never reconstruct the cwd-slug
// encoding. Each line has a top-level `type`; the conversation is reconstructed
// linearly (a full parentUuid DAG is overkill for a recent-history glance):
//   user prompt → assistant text/tool_use* … → final assistant text.
//
// Schema notes (from the 2026-06 prior-art survey, see docs/design/RESEARCH-…):
//   - message.content is `string | block[]`; user prompts are often a bare string.
//   - tool results come back as `user` events whose content is tool_result blocks
//     — those are NOT new prompts, so they don't open a turn.
//   - the FINAL assistant message has stop_reason=="end_turn" (tool_use is mid-turn);
//     we approximate by letting the latest assistant text win.
//   - isMeta (slash-command echo) and isSidechain (sub-agent) entries are skipped
//     so they don't pollute the main timeline.
//   - unknown `type` values (ai-title/queue-operation/attachment/…) are ignored.

type claudeLine struct {
	Type        string         `json:"type"`
	IsMeta      bool           `json:"isMeta"`
	IsSidechain bool           `json:"isSidechain"`
	Message     *claudeMessage `json:"message"`
}

type claudeMessage struct {
	Role       string          `json:"role"`
	Content    json.RawMessage `json:"content"`
	StopReason string          `json:"stop_reason"`
}

type claudeBlock struct {
	Type  string          `json:"type"`
	Text  string          `json:"text"`
	Name  string          `json:"name"`
	Input json.RawMessage `json:"input"`
}

func claudeLogPath(sessionID string) string {
	matches, _ := filepath.Glob(filepath.Join(claudeProjectsDir(), "*", sessionID+".jsonl"))
	if len(matches) > 0 {
		return matches[0]
	}
	return ""
}

func claudeProjectsDir() string {
	return filepath.Join(os.Getenv("HOME"), ".claude", "projects")
}

// claudeStep folds one Claude log line into the parse state: a real user prompt
// opens a turn; tool_result-only user events are skipped; assistant text/tool_use
// extend the open turn (latest text wins → the final reply).
func claudeStep(line string, st *parseState) {
	var e claudeLine
	if json.Unmarshal([]byte(line), &e) != nil || e.Message == nil || e.IsSidechain {
		return
	}
	switch e.Type {
	case "user":
		if e.IsMeta {
			return
		}
		prompt, isPrompt := claudePrompt(e.Message.Content)
		if !isPrompt {
			return // a tool_result-only user event — not a new turn
		}
		st.open(prompt)
	case "assistant":
		st.ensure() // tail may have started mid-turn (no preceding prompt)
		text, steps := claudeAssistant(e.Message.Content)
		if text != "" {
			st.cur.Response = text // latest assistant text wins → the final reply
		}
		st.cur.Steps = append(st.cur.Steps, steps...)
	}
}

// claudePrompt extracts a user-typed prompt from message.content. Returns ok=false
// when the content is a tool result (not a real prompt) or empty/meta wrapper.
func claudePrompt(raw json.RawMessage) (string, bool) {
	if len(raw) == 0 {
		return "", false
	}
	// content as a bare string (the common typed-prompt case).
	var s string
	if json.Unmarshal(raw, &s) == nil {
		return cleanPrompt(s)
	}
	// content as blocks: collect text, ignore tool_result-only payloads.
	var blocks []claudeBlock
	if json.Unmarshal(raw, &blocks) != nil {
		return "", false
	}
	var parts []string
	for _, b := range blocks {
		if b.Type == "text" && strings.TrimSpace(b.Text) != "" {
			parts = append(parts, strings.TrimSpace(b.Text))
		}
	}
	if len(parts) == 0 {
		return "", false // tool_result / image only
	}
	return cleanPrompt(strings.Join(parts, "\n"))
}

// harnessBlockRe strips the synthetic XML-ish blocks the Claude Code harness
// injects INTO user content — context reminders and background-task notices. They
// are not typed by the user, so they must never surface as chat prompts (a turn
// that is ONLY such a block collapses to empty and is dropped; one appended to a
// real prompt is just trimmed off).
var harnessBlockRe = regexp.MustCompile(`(?s)<(system-reminder|task-notification)>.*?</(system-reminder|task-notification)>`)

// cleanPrompt strips harness-injected blocks then rejects empty/meta wrappers,
// returning the displayable prompt and whether it's a real typed prompt.
func cleanPrompt(s string) (string, bool) {
	s = strings.TrimSpace(harnessBlockRe.ReplaceAllString(s, ""))
	if s == "" || isClaudeMetaPrompt(s) {
		return "", false
	}
	return s, true
}

// isClaudeMetaPrompt filters the synthetic wrappers Claude injects as "user"
// content (slash-command echoes, local-command stdout, the local-command caveat).
func isClaudeMetaPrompt(s string) bool {
	return strings.HasPrefix(s, "<command-") ||
		strings.HasPrefix(s, "<local-command-") ||
		strings.HasPrefix(s, "Caveat: The messages below were generated by the user while running local commands")
}

// claudeAssistant returns the concatenated text of an assistant message and its
// tool_use blocks as Steps.
func claudeAssistant(raw json.RawMessage) (string, []Step) {
	var blocks []claudeBlock
	if json.Unmarshal(raw, &blocks) != nil {
		// some assistant messages carry a bare string
		var s string
		if json.Unmarshal(raw, &s) == nil {
			return strings.TrimSpace(s), nil
		}
		return "", nil
	}
	var text []string
	var steps []Step
	for _, b := range blocks {
		switch b.Type {
		case "text":
			if strings.TrimSpace(b.Text) != "" {
				text = append(text, strings.TrimSpace(b.Text))
			}
		case "tool_use":
			steps = append(steps, Step{Kind: "tool", Title: b.Name, Detail: toolDetail(b.Input)})
		}
	}
	return strings.TrimSpace(strings.Join(text, "\n")), steps
}

// toolDetail picks a short, human-meaningful summary from a tool_use input object
// (file path / command / pattern / url …).
func toolDetail(input json.RawMessage) string {
	if len(input) == 0 {
		return ""
	}
	var m map[string]any
	if json.Unmarshal(input, &m) != nil {
		return ""
	}
	for _, k := range []string{"file_path", "path", "command", "pattern", "url", "query", "description", "prompt"} {
		if v, ok := m[k]; ok {
			if s, ok := v.(string); ok && strings.TrimSpace(s) != "" {
				return clip(s, 80)
			}
		}
	}
	return ""
}
