package transcript

import "testing"

// CleanUserPrompt must drop every class of system-injected content but pass a real
// user prompt through untouched — the fix for a `<task-notification>` fragment being
// read back as a session goal.
func TestCleanUserPrompt(t *testing.T) {
	cases := []struct {
		name   string
		in     string
		want   string
		wantOK bool
	}{
		{"real prompt", "cut a new release", "cut a new release", true},
		{"closed task-notification", "<task-notification> <task-id>b50xphl27</task-id> done </task-notification>", "", false},
		// The exact leaked fragment: an UNCLOSED/truncated task-notification.
		{"truncated task-notification", "<task-notification> <task-id>b50xphl27</", "", false},
		{"system-reminder block", "<system-reminder>context is running low</system-reminder>", "", false},
		{"truncated system-reminder", "<system-reminder>context is running", "", false},
		{"task-notification with attrs", `<task-notification id="x"> bg task done </task-notification>`, "", false},
		{"SYSTEM NOTIFICATION line", "[SYSTEM NOTIFICATION 2026-07-13] a background task finished", "", false},
		{"gtmux nudge echoed back", `[gtmux] goal-changed gtmux:0 (%20) — goal:"do the thing"`, "", false},
		// Injected content APPENDED to a real prompt → keep only the real prompt.
		{"real + trailing reminder", "fix the bug\n<system-reminder>note</system-reminder>", "fix the bug", true},
		{"real + trailing nudge", "ship it\n[gtmux] done gtmux:0 (%1) — goal:\"x\"", "ship it", true},
		{"real + leading task-notification", "<task-notification>done</task-notification>\nnow do X", "now do X", true},
		{"empty", "   ", "", false},
		// The CURRENT wake format echoed back — the retired `[gtmux]` prefix was the
		// only one this knew, so our own signal line could read back as a user goal.
		{"wake line echoed back", `» gtmux·done  gtmux:0.0 (%14) │ 3m │ goal:"ship it"`, "", false},
		{"real + trailing wake line", "ship it\n» gtmux·tick  │ 2 done", "ship it", true},
		// A slash command is not typed prose (CleanUserPrompt says no) — see
		// TestClassifyUserPrompt for what it IS.
		{"slash command", "<command-name>/compact</command-name>", "", false},
	}
	for _, c := range cases {
		got, ok := CleanUserPrompt(c.in)
		if got != c.want || ok != c.wantOK {
			t.Errorf("%s: CleanUserPrompt(%q) = (%q, %v), want (%q, %v)", c.name, c.in, got, ok, c.want, c.wantOK)
		}
	}
}

// ClassifyUserPrompt separates "the user did something" from "this rendered as a chat
// turn". A slash command is the first without being the second — it used to be
// dropped as neither, so a `/compact` in an agent window reached HQ as silence.
func TestClassifyUserPrompt(t *testing.T) {
	cases := []struct {
		name     string
		in       string
		wantText string
		wantKind string
	}{
		{"typed prose", "cut a new release", "cut a new release", PromptUser},
		{"slash command", "<command-name>/compact</command-name>", "/compact", PromptSlash},
		{"slash with message + args", "<command-name>/deploy</command-name>\n<command-message>deploy</command-message>\n<command-args>staging</command-args>", "/deploy", PromptSlash},
		{"slash, unreadable name", "<command-name>", "", PromptSlash},
		// Command OUTPUT is not an act — the act was the command, which already waked.
		{"local command stdout", "<local-command-stdout>files changed</local-command-stdout>", "", PromptDrop},
		{"local command caveat", "Caveat: The messages below were generated by the user while running local commands. blah", "", PromptDrop},
		{"harness injection only", "<system-reminder>context is running low</system-reminder>", "", PromptDrop},
		{"our own wake line", "» gtmux·waiting  gtmux:0.0 (%14)", "", PromptDrop},
		{"empty", "  ", "", PromptDrop},
		// The filter used to match the loose `<command-` prefix; a real prompt that
		// merely opens with an angle bracket is prose, not a wrapper.
		{"prose starting with a tag-ish word", "<command-line parsing> is broken, fix it", "<command-line parsing> is broken, fix it", PromptUser},
	}
	for _, c := range cases {
		text, kind := ClassifyUserPrompt(c.in)
		if text != c.wantText || kind != c.wantKind {
			t.Errorf("%s: ClassifyUserPrompt(%q) = (%q, %q), want (%q, %q)",
				c.name, c.in, text, kind, c.wantText, c.wantKind)
		}
	}
}
