// Generated by scripts/gen-release-notes.sh from mobileapp/release-notes/ — do not edit by
// hand. One entry per shipped version, NEWEST FIRST, so a user who skipped versions sees
// every one they crossed. scripts/check-design.sh fails when this file and the archive
// disagree; re-run mobileapp/scripts/set-version.sh to fix.

/** One shipped version's user-facing notes, in both languages. */
export interface ReleaseNote {
  version: string;
  en: string[];
  zh: string[];
}

export const RELEASE_NOTES: ReleaseNote[] = [
  {
    version: '0.77.0',
    en: [
      'The HQ page has a slimmer header, so the conversation finally has room.',
      'New: see what your supervisor did while you were away. Dispatches, clean-ups, the notes it kept.',
      'HQ\'s steps now show while it works, instead of folding away once it finishes.',
    ],
    zh: [
      'HQ 页头部瘦身，对话终于有地方了。',
      '新增：看得到参谋长替你做了什么。派活、回收、记的账都在这里。',
      'HQ 干活的过程边跑边看，不用等它跑完再去角落里翻。',
    ],
  },
  {
    version: '0.76.0',
    en: [
      'Fixed: a session\'s agent icon could turn into a plain two-letter mark and stay that way. One icon request failing on a weak connection was being treated as "this agent has no icon"; it now retries.',
    ],
    zh: [
      '修复：会话的 agent 图标有时会变成两个字母的字标，并且一直不恢复。以前只要有一次取图在弱网下失败，就被当成「这个 agent 没有图标」；现在会重试。',
    ],
  },
  {
    version: '0.74.0',
    en: [
      'Fixed: the lock-screen Live Activity counted gtmux\'s own supervisor as work in progress — it now counts only your sessions.',
      'Fixed: the lock-screen card could freeze hours behind — the app now keeps making sure this Mac can still push to it.',
      'Long-pressing a session now shows the full task and error, which pane it is, and one step to go look at it on the Mac.',
    ],
    zh: [
      '修复：锁屏实时活动把 gtmux 自己的中控算成了「工作中」，现在只统计你的会话。',
      '修复：锁屏卡片可能停在几小时前的状态不再更新 —— 现在会持续确保 Mac 能推送到它。',
      '长按一个会话现在给出完整任务与错误原文、它是哪个 pane，以及一步跳到 Mac 上去看。',
    ],
  },
  {
    version: '0.72.0',
    en: [
      'Fixed: the lock-screen Live Activity counted gtmux\'s own supervisor as work in progress — it now counts only your sessions.',
      'Fixed: the lock-screen card could freeze hours behind — the app now keeps making sure this Mac can still push to it.',
    ],
    zh: [
      '修复：锁屏实时活动把 gtmux 自己的中控算成了「工作中」，现在只统计你的会话。',
      '修复：锁屏卡片可能停在几小时前的状态不再更新 —— 现在会持续确保 Mac 能推送到它。',
    ],
  },
  {
    version: '0.67.0',
    en: [
      'Fixed: when an agent moved its conversation to a background process, the phone kept showing the old history.',
      'The chat now refreshes on its own instead of waiting for the pane\'s status to change.',
    ],
    zh: [
      '修复：agent 把对话搬到后台运行后，手机上的对话会停在旧记录不再更新。',
      '对话页现在自己会刷新，不用等状态变化。',
    ],
  },
  {
    version: '0.64.0',
    en: [
      'A session whose turn ended on a failure now has its own "errored" group, amber, right below the ones waiting for you — instead of sitting under a green tick among the finished ones.',
      'The situation board honours the line breaks the supervisor writes instead of printing the tag and running everything together, and struck-out items look struck out.',
      'Picking panes for a share link groups them by session and leads each row with its pane id; a link\'s summary counts only the panes it can still reach.',
    ],
    zh: [
      '停在错误上的会话现在有了自己的「出错」分区（琥珀色），紧挨在「需要你」下面 —— 而不是顶着绿勾躺在已完成里。',
      '态势板现在会遵守参谋长写的换行，而不是把标签原样打出来、把内容挤成一整段；划掉的条目也真的显示为划掉。',
      '给分享链接挑 pane 时按 session 分组、每行以 pane id 打头；链接摘要只数它还能到达的 pane。',
    ],
  },
  {
    version: '0.62.0',
    en: [
      'Version alignment with gtmux 0.62.0 — this release hardens the CLI/HQ side (loss-proof perception, a fully bilingual supervisor charter); no phone-side changes.',
    ],
    zh: [
      '与 gtmux 0.62.0 版本对齐 —— 本次加固都在 CLI/中控侧（不丢事件的感知、整份双语守则），手机端无功能变化。',
    ],
  },
  {
    version: '0.61.0',
    en: [
      'Version alignment with gtmux 0.61.0 — this release\'s improvements are on the CLI/HQ side (a supervisor that speaks to any user); no phone-side changes.',
    ],
    zh: [
      '与 gtmux 0.61.0 版本对齐 —— 本次改进都在 CLI/中控侧（面向任何用户的参谋长），手机端无功能变化。',
    ],
  },
  {
    version: '0.59.0',
    en: [
      'Picking panes for a share link now groups them by session and leads each row with its pane id, so two panes running the same project are no longer two identical-looking rows.',
      'A share link\'s summary counts the panes it can still reach and names the grants whose pane is gone; when tmux has restarted, the app says the links are being refused and how to restore them.',
      '"All panes" and Settings no longer overlap each other\'s tap areas.',
    ],
    zh: [
      '给分享链接挑 pane 时按 session 分组、每行以 pane id 打头 —— 两个跑着同一个项目的 pane，不再是两行长得一模一样、无从分辨的选项。',
      '分享链接的摘要只数它还能到达的 pane，并把已失效的授权明说出来；tmux 重启之后，app 会直说这些链接正被拒绝以及如何恢复。',
      '「所有 pane」和「设置」的点击区不再重叠。',
    ],
  },
  {
    version: '0.58.1',
    en: [
      '"All panes" and Settings no longer overlap each other\'s tap areas — aiming at the right half of "all panes" used to open Settings.',
      'A row marked "background running" names the actual command instead of a script\'s first line, which was often just a variable assignment.',
      'A share link\'s summary counts the panes it can still reach and names the grants whose pane is gone; when tmux has restarted, the app now says the links are being refused and how to restore them.',
    ],
    zh: [
      '「所有 pane」和「设置」的点击区不再重叠 —— 以前瞄准「所有 pane」右半边点，开的是设置。',
      '标着「后台运行中」的行现在显示真正的命令，而不是脚本的第一行（那往往只是个变量赋值）。',
      '分享链接的摘要只数它还能到达的 pane，并把已失效的授权明说出来；tmux 重启之后，app 会直说这些链接正被拒绝以及如何恢复。',
    ],
  },
  {
    version: '0.57.1',
    en: [
      'Paired devices now say what they ARE (iOS 26.6, Chrome 141 · macOS) and where they last connected from, and the list finally has an order — most recently seen first.',
      'A share link says whether anyone has used it, and from what device — or "not used yet", which is worth knowing about a link you handed out.',
    ],
    zh: [
      '配对设备现在会说出它是什么（iOS 26.6、Chrome 141 · macOS）和上次从哪连的，列表也终于有了顺序 —— 最近连接的排在前面。',
      '分享链接会说出有没有人用过、用的什么设备；没人用过就直说「还没有人用过」—— 对一份你发出去的链接来说，这是值得知道的。',
    ],
  },
  {
    version: '0.55.1',
    en: [
      'The all-panes browser draws the window line for every session now, including one that holds a single window, and a pane row sits indented inside its window instead of starting further left than the window line above it.',
      'A pane row no longer repeats the agent\'s name under its icon; the text says what the pane is doing.',
    ],
    zh: [
      '「所有 pane」浏览器现在每个 session 都画出窗口那一行（包括只有一个窗口的），pane 行也缩进在它所属的窗口里面，不再比上面那行窗口名还靠左。',
      'pane 行不再在图标下面重复 agent 名字，文字留给「这个 pane 在做什么」。',
    ],
  },
  {
    version: '0.55.0',
    en: [
      'The all-panes browser draws the window line for every session now, including one that holds a single window — the tree has the same shape everywhere instead of two shapes a row apart.',
      'A pane row no longer repeats the agent\'s name under its icon; the text says what the pane is doing.',
    ],
    zh: [
      '「所有 pane」浏览器现在每个 session 都画出窗口那一行，包括只有一个窗口的 —— 整棵树到处都是同一个形状，不再隔一行换一种。',
      'pane 行不再在图标下面重复 agent 名字，文字留给「这个 pane 在做什么」。',
    ],
  },
  {
    version: '0.54.0',
    en: [
      'The HQ situation board reads like a document again: wide tables stack into labelled blocks instead of running off the side of the screen, and inline code no longer leaves white marks through the prose.',
      'The board sheet stops repeating its own title, and says how long ago it was updated.',
    ],
    zh: [
      '中控态势板恢复成一份能读的文档：过宽的表格改为逐行堆叠并带上列名，不再从屏幕右侧跑掉；行内代码也不再在正文里留下一块块白斑。',
      '态势板页面不再把自己的标题重复一遍，改为直接告诉你它多久前更新过。',
    ],
  },
  {
    version: '0.53.0',
    en: [
      'The all-panes browser now shows the window level: panes are grouped under the window that holds them, and a session\'s header lists its windows even when folded.',
      'Every row leads with its pane id (%23) instead of a position that changes whenever panes are reordered. Tap the id to copy "gtmux focus %23".',
      'Search finds a pane by id too — %23, @17, or just the digits.',
    ],
    zh: [
      '「所有 pane」浏览器现在会显示窗口这一层：pane 按所属窗口分组，会话折叠起来时头部也会列出它有哪些窗口。',
      '每一行改为以 pane id（%23）开头，不再用会随重排而变的位置编号。点 id 即可复制 "gtmux focus %23"。',
      '搜索也能用 id 找 pane —— %23、@17，或直接敲数字。',
    ],
  },
  {
    version: '0.52.0',
    en: [
      'A notification\'s quick-reply buttons no longer claim a meaning they cannot know. They showed the same "1 · Yes / 2 · Always / 3 · No" whatever the agent was asking, so on a two-option prompt the button labelled Always sent the answer that means No. They now show only the number, the body lists the real options one per line, and there are exactly as many buttons as the agent offers.',
      'Long-pressing a notification shows the question instead of a giant coloured square.',
      'The HQ situation board reads as sections you can fold, and its headings are legible again instead of drowning in bold.',
    ],
    zh: [
      '通知的快回按钮不再声称它不知道的含义。以前不管 agent 在问什么，都显示同样的「1 · Yes / 2 · Always / 3 · No」——于是在两项提示上，标着 Always 的按钮发出去的答案其实是「No」。现在按钮只显示编号，正文一行一个列出真实选项，按钮个数与 agent 提供的一致。',
      '长按通知看到的是问题本身，而不是一大块彩色方块。',
      '中控态势板改成可折叠的分节，标题不再淹没在满屏加粗里。',
    ],
  },
  {
    version: '0.51.2',
    en: [
      'A session that is working now says so with a ring that turns, matching the Mac. It stays slow and calm — urgency is red, and red never moves. Reduce Motion is honoured.',
      'Rows no longer read "◐ my task name" when the agent on your Mac animates a spinner in its window title.',
    ],
    zh: [
      '正在工作的会话现在用一枚会转的环表示，与 Mac 端一致。转速很慢：着急是红色的事，而红色永不动。尊重系统的「减弱动态」。',
      '行里不会再出现「◐ 我的任务名」—— Mac 上的 agent 把转圈动画写在窗口标题里时，不会再漏到这里。',
    ],
  },
  {
    version: '0.51.1',
    en: [
      'The built-in demo now shows the same app the radar does: the all-panes browser, the fleet tally, and the waiting-only filter were missing from it.',
      'A few Chinese strings reworded.',
    ],
    zh: [
      '内置演示现在和真实雷达是同一个 app：之前它缺了「所有 pane」浏览器、舰队计数和「只看等输入」筛选。',
      '几处中文文案修订。',
    ],
  },
  {
    version: '0.50.0',
    en: [
      'The HQ page now speaks up about two things it used to stay quiet on: when the supervisor itself needs a decision from you, and when the Mac is genuinely short of disk, memory or power. It reported "all normal — nothing needs you" in both cases, while the Mac\'s own menu bar said otherwise about the very same fleet at the very same moment. That verdict is now decided once, on the Mac, and this app renders it — so the two can no longer disagree.',
    ],
    zh: [
      'HQ 页面现在会对两件它以前一声不吭的事开口：中控自己需要你拍板时，以及 Mac 真的磁盘、内存或电量吃紧时。这两种情况下它以前都显示「都正常 · 无需你介入」，而同一时刻、同一个舰队，Mac 上的菜单栏说的却是另一回事。这个判断现在由 Mac 端裁定一次，本 app 只负责呈现 —— 两边不会再各说各的。',
    ],
  },
  {
    version: '0.48.4',
    en: [
      'A link the terminal had to wrap onto a second line is one link again. A long URL used to be cut where the row ended, and only the first fragment was tappable — so it opened a host that did not exist while the real address sat below it as plain text. Every piece of a wrapped URL now opens the whole thing, including a URL the terminal recolours half-way through.',
      'Fewer false alarms in the radar: a session that merely SHOWS the words of a startup trust prompt — because you were reading or discussing them — is no longer reported as an agent stuck waiting for you, and a session that finishes while such text is on screen is no longer silently skipped. Needs gtmux 0.48.4 on the Mac.',
    ],
    zh: [
      '被终端折到第二行的链接，现在重新是一条完整链接。以前长 URL 会在行尾被切断，只有前半截可点 —— 于是点开的是一个并不存在的域名，而真正的地址就在下面躺着、还点不了。现在折行后的每一段都能打开完整地址，中途变色的 URL 也一样。',
      '雷达的误报变少了：屏幕上只是「出现」了启动信任提示的字样（你在读它、或者在讨论它），不再被报成有 agent 卡住等你；带着这类文字干完活的会话，也不会再被悄悄漏掉。需要 Mac 端升级到 gtmux 0.48.4。',
    ],
  },
  {
    version: '0.48.1',
    en: [
      'A conversation that looks empty now explains itself: a session started over with /clear or /new says which moment it starts from, and points at Activity for the record from before. A wiped supervisor history used to read as a broken app.',
      'The What\'s New card you are reading scrolls properly — it used to barely move — and now carries the gtmux mark and a single version chip instead of printing the version twice.',
      'Diff appears only where it can work: a pane sitting in a git repository offers it, and one outside a repository no longer shows a control that could only fail.',
      'Needs gtmux 0.48.1 on the Mac for the cleared-conversation notice; the rest works with what you have.',
    ],
    zh: [
      '看起来空白的会话现在会自己交代来龙去脉：以 /clear 或 /new 重新开始的会话会说明本轮从哪一刻起算，并指向「动态」查看更早的记录。以前中控的历史被清空，看上去就像 app 坏了。',
      '你正在读的这张「更新内容」卡片能正常滚动了 —— 以前几乎推不动 —— 并且带上了 gtmux 标识，版本号只显示一次，不再重复。',
      'Diff 只在能用的地方出现：位于 git 仓库里的 pane 才提供它，不在仓库里的 pane 不再显示一个注定失败的按钮。',
      '「会话已清空」这条提示需要 Mac 端升级到 gtmux 0.48.1；其余改动用现在的版本就能看到。',
    ],
  },
  {
    version: '0.47.0',
    en: [
      'What\'s new: after an update the app tells you what changed — every version you skipped, not just the latest. Read it again any time from Settings.',
      'Numbered lists in a reply are numbered again: 1, 2, 3 rather than 1, 1, 1. An item\'s wrapped text used to break the list apart.',
      'Landscape: the exit-full-screen button no longer covers the first line, content stays clear of the notch, and a phone keeps its single-column layout instead of borrowing the iPad\'s two-column one.',
      'With gtmux updated on the Mac: sending into a pane where you have unsent text is refused instead of swallowing it, a failed send can be retried straight away, and agents with no desktop app show their real icon.',
    ],
    zh: [
      '更新内容：升级后会告诉你改了什么 —— 你跳过的每个版本都会列出，而不只是最新那条。设置里随时可以再看一遍。',
      '回复里的有序列表重新会数数了：1、2、3，而不是 1、1、1。以前条目里换行的正文会把列表截断。',
      '横屏：退出全屏的按钮不再压住第一行；正文避开刘海；手机保持单栏布局，不再套用 iPad 的双栏。',
      '配合 Mac 端更新：往你有未提交内容的 pane 发消息会被拒绝，而不是把它吞掉；发送失败后可以直接重试；没有桌面 app 的 agent 也能显示真实图标。',
    ],
  },
  {
    version: '0.45.13',
    en: [
      'Native text selection in the terminal — long-press to select with the system handles and magnifier; Copy takes exactly what you selected.',
      'The terminal now renders as a true grid — typing and scrolling in a busy pane is much faster, and scrollback goes back 1,000 lines.',
      'Send now dismisses the keyboard, and the key row gains a backspace key.',
      'Fullscreen is a clean reading mode — the input bar gets out of the way.',
      'Polish: empty panes no longer show a black screen, multi-line input is no longer clipped, long diff lines scroll sideways, pane rows show the agent\'s name, and Snippets are now Quick replies.',
      'With gtmux updated on the Mac: typing into a plain (non-agent) pane no longer falsely reports a failure, and the Warp terminal is supported.',
    ],
    zh: [
      '终端支持原生文本选中：长按呼出系统选中手柄与放大镜，Copy 精确复制选中内容。',
      '终端改为真正的网格渲染：忙碌会话里打字、滚动明显更快，历史回看加深到 1000 行。',
      '发送后自动收起键盘；按键行新增退格键。',
      '全屏即纯阅读模式，输入条自动隐藏。',
      '打磨：空内容 pane 不再黑屏；多行输入不再被裁切；Diff 长行可横向滑动；pane 列表显示 agent 名称；「Snippets」更名「常用语」。',
      '配合 Mac 端更新：往普通终端 pane（非 agent 会话）输入不再误报失败；新增 Warp 终端支持。',
    ],
  },
];
