// Generated by scripts/gen-release-notes.sh from mobileapp/release-notes/ — do not edit by
// hand. One entry per shipped version, NEWEST FIRST, so a user who skipped versions sees
// every one they crossed. scripts/check-design.sh fails when this file and the archive
// disagree; re-run mobileapp/scripts/set-version.sh to fix.

/** One shipped version's user-facing notes, in both languages. */
export interface ReleaseNote {
  version: string;
  en: string[];
  zh: string[];
}

export const RELEASE_NOTES: ReleaseNote[] = [
  {
    version: '0.45.13',
    en: [
      'Native text selection in the terminal — long-press to select with the system handles and magnifier; Copy takes exactly what you selected.',
      'The terminal now renders as a true grid — typing and scrolling in a busy pane is much faster, and scrollback goes back 1,000 lines.',
      'Send now dismisses the keyboard, and the key row gains a backspace key.',
      'Fullscreen is a clean reading mode — the input bar gets out of the way.',
      'Polish: empty panes no longer show a black screen, multi-line input is no longer clipped, long diff lines scroll sideways, pane rows show the agent\'s name, and Snippets are now Quick replies.',
      'With gtmux updated on the Mac: typing into a plain (non-agent) pane no longer falsely reports a failure, and the Warp terminal is supported.',
    ],
    zh: [
      '终端支持原生文本选中：长按呼出系统选中手柄与放大镜，Copy 精确复制选中内容。',
      '终端改为真正的网格渲染：忙碌会话里打字、滚动明显更快，历史回看加深到 1000 行。',
      '发送后自动收起键盘；按键行新增退格键。',
      '全屏即纯阅读模式，输入条自动隐藏。',
      '打磨：空内容 pane 不再黑屏；多行输入不再被裁切；Diff 长行可横向滑动；pane 列表显示 agent 名称；「Snippets」更名「常用语」。',
      '配合 Mac 端更新：往普通终端 pane（非 agent 会话）输入不再误报失败；新增 Warp 终端支持。',
    ],
  },
];
