// Generated by scripts/gen-release-notes.sh from mobileapp/release-notes/ — do not edit by
// hand. One entry per shipped version, NEWEST FIRST, so a user who skipped versions sees
// every one they crossed. scripts/check-design.sh fails when this file and the archive
// disagree; re-run mobileapp/scripts/set-version.sh to fix.

/** One shipped version's user-facing notes, in both languages. */
export interface ReleaseNote {
  version: string;
  en: string[];
  zh: string[];
}

export const RELEASE_NOTES: ReleaseNote[] = [
  {
    version: '1.0.7',
    en: [
      'The situation board folds a long paragraph instead of printing all of it. One cell there had grown into an investigation log — about 1,180 characters on a single line — and it arrived as a wall of text. Tap to open one when you want the whole thing.',
      'The fold is on the board only. Chat and the knowledge base are prose written for you to read, where folding would hide the thing you just opened.',
    ],
    zh: [
      '态势板会把长段落折起来，不再整个铺开。板上一格曾长成一份排查记录 —— 一行约 1180 字 —— 到手就是一堵墙。想看全文点一下展开。',
      '折叠只在看板上做。对话和知识库是写给你读的东西，在那里折叠等于藏起你刚点开的内容。',
    ],
  },
  {
    version: '1.0.6',
    en: [
      'The knowledge base now says how it is organised. "Newest" and the topics are the same entries — newest is the base cut at the six most recent, and every one of them also sits under its topic — which the screen never said out loud.',
      'A topic folds open where it is instead of only being enterable, and coming back from an entry returns you to the list you opened it from, at the place you left it.',
    ],
    zh: [
      '知识库现在会说清自己是怎么组织的。「最近」和「主题」是同一批条目 —— 最近就是全库取最新几条，每一条同时也在自己的主题里 —— 这件事界面原本从没说过。',
      '主题可以就地展开，不再只能进去；从条目退出来会回到你原来那份列表、原来那个位置。',
    ],
  },
  {
    version: '1.0.5',
    en: [
      'Attaching a photo opens the markup editor again, and a staged thumbnail is tappable when you want to re-annotate one. Choosing from the attach sheet still opens the picker immediately, with no return trip through the input bar.',
      'The demo tour was missing the whole knowledge base and most of the usage page. Both are there now, shaped the way the real ones are.',
    ],
    zh: [
      '附加照片重新回到「选完直接进标注编辑器」，暂存的缩略图可以点开重新标注。从卡片里选完仍然立刻打开选择器，中间不再绕回输入栏。',
      '演示里整块知识库和大半个用量页是空的，现在都补上了，形状和真实数据一致。',
    ],
  },
  {
    version: '1.0.4',
    en: [
      'Full screen is actually full screen now. The top of the screen was holding about 100pt for a status bar that full screen had already hidden — portrait gains roughly eleven more lines of output, landscape about a quarter more reading area. The way out is a smaller, cleaner icon, and jumping back to the live tail is an arrow standing on a line.',
      'The plan sheet no longer drops an agent it cannot read. Codex reports its quota through its own session log, so a day without using it made every Codex row disappear, which looked the same as the app failing to read them. Codex now keeps its place and says that one turn brings the figure back.',
      'Attaching a photo is a shorter trip. Choosing from the sheet no longer waits for it to slide away before the picker opens, and a picked photo goes straight into the composer instead of through the markup editor — tap the thumbnail when you do want to annotate.',
    ],
    zh: [
      '全屏现在是真的全屏。屏幕顶部之前替一根全屏时早已隐藏的状态栏留着约 100pt —— 竖屏多出约十一行输出，横屏阅读区多出约四分之一。退出的图标更小更干净，回到实时尾部的按钮换成「箭头落在一根线上」。',
      '额度页不再把读不到的 agent 直接丢掉。Codex 靠自己的会话日志上报额度，一天不用它，它的行就全部消失，看起来跟 app 读不到一模一样。现在 Codex 会留在原位，并说明跑一轮就能把数字读回来。',
      '加照片这条路短了。从卡片里选完不再等它滑走才打开选择器，选中的照片也直接进输入框，不再被推进标注编辑器 —— 想标注时点一下缩略图即可。',
    ],
  },
  {
    version: '1.0.3',
    en: [
      'Full screen is actually full screen now. The top of the screen was holding about 100pt for a status bar that full screen had already hidden — portrait gains roughly eleven more lines of output, landscape about a quarter more reading area. The way out is a smaller, cleaner icon, and jumping back to the live tail is an arrow standing on a line.',
      'The plan sheet no longer drops an agent it cannot read. Codex reports its quota through its own session log, so a day without using it made every Codex row disappear, which looked the same as the app failing to read them. Codex now keeps its place and says that one turn brings the figure back.',
    ],
    zh: [
      '全屏现在是真的全屏。屏幕顶部之前替一根全屏时早已隐藏的状态栏留着约 100pt —— 竖屏多出约十一行输出，横屏阅读区多出约四分之一。退出的图标更小更干净，回到实时尾部的按钮换成「箭头落在一根线上」。',
      '额度页不再把读不到的 agent 直接丢掉。Codex 靠自己的会话日志上报额度，一天不用它，它的行就全部消失，看起来跟 app 读不到一模一样。现在 Codex 会留在原位，并说明跑一轮就能把数字读回来。',
    ],
  },
  {
    version: '1.0.2',
    en: [
      'Full screen is actually full screen now. The top of the screen was holding about 100pt for a status bar that full screen had already hidden — portrait gains roughly eleven more lines of output, landscape about a quarter more reading area. The way out is a smaller, cleaner icon, and jumping back to the live tail is an arrow standing on a line.',
    ],
    zh: [
      '全屏现在是真的全屏。屏幕顶部之前替一根全屏时早已隐藏的状态栏留着约 100pt —— 竖屏多出约十一行输出，横屏阅读区多出约四分之一。退出的图标更小更干净，回到实时尾部的按钮换成「箭头落在一根线上」。',
    ],
  },
  {
    version: '1.0.1',
    en: [
      'Leaving full screen is a small icon in the app\'s own blue instead of a button as wide as the words "Exit full screen", and it no longer floats a gap below the Dynamic Island.',
    ],
    zh: [
      '退出全屏改成一个品牌色的小图标，不再是一枚跟「退出全屏」这几个字一样宽的按钮，也不再在灵动岛下面空出一段距离。',
    ],
  },
  {
    version: '1.0.0',
    en: [
      'A long list of changes since the last release. The ones you will notice:',
      'The supervisor\'s knowledge base is readable from the phone, and you can close out a promoted lesson without going to the Mac.',
      'A usage view: which plan window you are in, who is burning it, and what the machine is doing.',
      'The situation board reads as an outline. Sections and entries open one at a time, and each pane stays folded until you want it, so a long board is a list you can scan instead of a document you scroll past.',
      'The HQ page reports like a chief of staff rather than an instrument panel: what is owed, what was done, where you stand.',
      'A half-typed message survives leaving the pane, and input history follows the work you are in rather than being one global list.',
      'A send tells you what happened to it: which refusal it hit, or that the session is mid-turn and it will be handled when that turn ends.',
      'The phone can keep a copy of the supervisor\'s memory, which rides your iPhone\'s own backup.',
      'Neighbour panes carry their real names, jumping to a session is a first-class action, and the connection state reaches a screen reader.',
    ],
    zh: [
      '距上次发布积攒了很多改动。你会注意到的是这些：',
      '中控的知识库可以在手机上读了，晋升的条目也能直接在手机上闭环，不用回 Mac。',
      '新增用量页：你在哪个额度窗口里、谁在烧、机器状况如何。',
      '态势板改成大纲。分节和条目一条条点开，每个 pane 默认折着，长长的板子变成一份能扫的列表，而不是一篇要一路划过去的文档。',
      'HQ 页像参谋长汇报，不像仪表盘：欠着什么、做了什么、你现在站在哪。',
      '打了一半的消息在你离开会话后还在，输入历史跟着你手上的活走，不再是一个全局列表。',
      '发消息会告诉你结果：撞上了哪种拒绝，或者那个会话正在跑、这条会在本回合结束后处理。',
      '手机可以留一份中控记忆的副本，跟着 iPhone 自己的备份走。',
      '相邻 pane 显示真实名字，跳到某个会话是一等操作，连接状态也能被读屏软件念出来。',
    ],
  },
  {
    version: '0.99.0',
    en: [
      'The situation board no longer shows the note its author leaves for whoever edits it next. It used to be the first line you read under a heading.',
      'A folded pane on the board is a row rather than a boxed card, so a section of thirteen panes reads as a list you can scan instead of a stack of boxes.',
    ],
    zh: [
      '态势板不再把作者留给下一个编辑者的备注渲染出来，那句话以前就顶在标题下面第一行。',
      '板子上折起来的 pane 现在是一行、不是一个方框，十三个 pane 读起来是一份能扫的列表，不是一摞盒子。',
    ],
  },
  {
    version: '0.98.0',
    en: [
      'Each pane on the situation board stays folded until you open it. A section of thirteen panes is thirteen rows you can scan, instead of several screens of text with the one you wanted somewhere inside.',
      'A closed row shows where the pane is, so you can find the right one without opening any of them.',
    ],
    zh: [
      '态势板上的每个 pane 默认折着，点开才展开。十三个 pane 的那一节现在是十三行、扫一眼就够，不再是好几屏字、而你要找的那个埋在里面。',
      '折起来的行会显示这个 pane 在哪，不用挨个点开就能找到对的那个。',
    ],
  },
  {
    version: '0.97.0',
    en: [
      'The situation board opens as a real outline. Every entry is its own row, so a long handoff section is no longer a wall of text to scroll past, or a screen of nothing. Opening one is instant now.',
      'A section\'s count says what it holds, not how many lines it was typed on.',
    ],
    zh: [
      '态势板改成真正的大纲，每条记录自己一行。长长的交接记录不再是一堵要一路划过去的墙，也不再是一屏空白。展开现在是瞬间的。',
      '分节的计数说的是它装了什么，不是它被敲了多少行。',
    ],
  },
  {
    version: '0.96.0',
    en: [
      'The usage view now says what each figure means: the plan is grouped by agent, and the token totals are labelled as what they are rather than mistaken for a billing period.',
      'Lists end with a mark instead of a line of text.',
    ],
    zh: [
      '用量页说清了每个数字的含义：额度按 agent 分组，token 总量标明了它到底算的是什么，不会再被当成某个计费周期。',
      '列表末尾改用一个记号收尾，不再写一行字。',
    ],
  },
  {
    version: '0.95.0',
    en: [
      'A usage view on the phone: your plan windows, who is burning them, and the machine — reached from the HQ page.',
      'Sessions there are ranked by trouble rather than size, so the one that needs attention is at the top.',
    ],
    zh: [
      '手机上有了用量页：额度窗口、谁在烧、机器状况，从 HQ 页进去。',
      '里面的会话按「麻烦」排而不是按「大小」排，需要你留意的那条在最上面。',
    ],
  },
  {
    version: '0.94.0',
    en: [
      'The HQ page now reports instead of displaying: what is owed to you, what HQ did, and only then the context — rather than a stack of readings you can see on the radar anyway.',
      'Input history is kept per project, so the message you want is at the top instead of buried under other work.',
    ],
    zh: [
      'HQ 页现在是汇报而不是罗列：先说欠你什么、参谋长做了什么，最后才是现状，不再堆一屏雷达上本来就有的读数。',
      '输入历史按项目保留，你要找的那条在最上面，不会被别的项目顶掉。',
    ],
  },
  {
    version: '0.93.0',
    en: [
      'A half-typed message now survives leaving the pane. Drafts are kept per session, so what you started writing is waiting when you come back.',
      'Token usage and plan limits now cover Codex as well as Claude, and every window says whose plan it is.',
    ],
    zh: [
      '打了一半的话不会再丢。草稿按会话保留，离开这一屏再回来，写到一半的内容还在。',
      '用量和额度现在也覆盖 Codex，不只是 Claude，每个额度窗口都写明属于谁的套餐。',
    ],
  },
  {
    version: '0.92.0',
    en: [
      'The radar says where it ends, so a list that stops no longer reads as one still loading.',
      'A row reporting an error gives that message the whole line, instead of squeezing the branch tag down to a blank pill.',
    ],
    zh: [
      '雷达会说明自己在哪儿结束，列表停住不再读起来像还在加载。',
      '报错的那一行把整行让给错误信息，不再把分支标签挤成一颗空白药丸。',
    ],
  },
  {
    version: '0.91.0',
    en: [
      'Scrolling is steady again. The header and tabs folding away used to fight the scroll position, so returning to the bottom jumped around, worst of all mid-conversation.',
      'A new reply no longer drags you out of the history you scrolled up to read.',
    ],
    zh: [
      '滚动稳了。顶部信息和标签折叠时会和滚动位置打架，回到底部就跳来跳去，对话进行中最明显。',
      '新回复不再把正在往上读历史的你拽回底部。',
    ],
  },
  {
    version: '0.90.0',
    en: [
      'The HQ page\'s verdict is now a card you can see is tappable, and what it opens is one grid instead of three stacked layouts.',
      'The header quotes the supervisor\'s latest word and stays quiet when that word was routine, so a withdrawn alert no longer sits there for hours.',
      'Tab and button capitalization follows one rule across the app.',
    ],
    zh: [
      'HQ 页的判断句现在是一张看得出能点的卡片，展开后是一张表，不再是三种排版摞在一起。',
      '头部只引参谋长的最新一句，例行流水账就什么都不说，作废的警报不会再挂几小时。',
      '标签和按钮的大小写全 app 统一成一条规则。',
    ],
  },
  {
    version: '0.89.0',
    en: [
      'The knowledge base now says what a promoted entry is: one the supervisor judged bigger than this machine, waiting for you to carry it somewhere durable.',
    ],
    zh: [
      '知识库现在会说清「待你带走」是什么：参谋长判断比这台机器大的条目，等你把它搬进一个持久的地方。',
    ],
  },
  {
    version: '0.88.0',
    en: [
      'A neighbour pane is named for what it is, not for the command it runs: three sibling shells no longer all read "bash".',
      'Each neighbour wears which kind it is, an agent its own icon and a shell the terminal mark.',
    ],
    zh: [
      '邻居 pane 按它实际是什么命名，而不是按它跑的命令：同一个会话里的三个 shell 不再全叫 bash。',
      '每个邻居戴上自己的身份图标：agent 是它自己的，shell 是终端标。',
    ],
  },
  {
    version: '0.83.0',
    en: [
      'The situation board reads as a list again: each session is its own card, and the count beside a section says what it holds instead of how many lines it was typed on.',
      'Amber now means one thing. The knowledge row turns amber only when a promotion has actually gone overdue, and each machine warning says what is wrong rather than just showing a reading.',
      'What HQ did no longer opens each line with an internal task id.',
    ],
    zh: [
      '态势板重新像一份清单：每条会话是一张独立卡片，分区旁的计数说的是它装了什么，而不是它被打了多少行字。',
      '琥珀色只表示一件事。知识库那行只在提升真的逾期时才转琥珀；机器告警会说清哪里不对，而不只是给一个读数。',
      '「参谋长做了什么」不再用内部任务 id 开头。',
    ],
  },
  {
    version: '0.82.0',
    en: [
      'A send that does not go through now says why: someone is typing in that pane, or the session is gone. The message you wrote is kept either way.',
      'A message sent to a session that is still working says it will be handled after the current turn.',
      'After the Mac compacts a conversation, the summary is no longer shown as something you said.',
      'The "thinking" timer is measured on the Mac\'s clock, so a phone whose clock is off no longer shows the wrong duration.',
      'Opening a turn\'s steps stays with that turn as the conversation grows.',
      'The connection dot now reads out to VoiceOver.',
    ],
    zh: [
      '消息没发出去时会说清原因：那个窗格里有人正在打字，或者会话已经不在了。无论哪种，你写的内容都会保留。',
      '发给正在跑的会话的消息，会提示它排在这一轮之后处理。',
      'Mac 压缩过对话之后，摘要不再被显示成你说过的话。',
      '「正在思考」的计时改用 Mac 的时钟，手机时间不准时不会再显示错误的时长。',
      '展开某一轮的步骤后，它会一直跟着那一轮，不会随着对话增长跑到别的回合上。',
      '连接状态的圆点现在能被 VoiceOver 读出来。',
    ],
  },
  {
    version: '0.81.0',
    en: [
      'HQ\'s knowledge base is now on the phone: read what the supervisor has learned, and mark a promoted lesson as landed once you have carried it somewhere.',
      'The HQ header was rebuilt. Its latest brief is attributed and dated, and the fleet, usage and machine figures are three readable rows instead of one gray sentence.',
      'Long press a session and jumping to it on the Mac is back near the top.',
      'Pull to refresh works again when every section is collapsed.',
    ],
    zh: [
      '参谋长的知识库现在能在手机上看了：读它学到了什么，并在你把一条已提升的经验带走之后标记落地。',
      'HQ 头部重做。最近一次简报有了署名和时间，舰队、用量、机器从一句灰句子拆成三行。',
      '长按会话，跳到 Mac 上那个会话的入口回到了靠前的位置。',
      '分区全部折叠时，下拉刷新恢复正常。',
    ],
  },
  {
    version: '0.80.0',
    en: [
      'The long-press sheet was rebuilt: it stops re-opening while you read it, leads with where the session is instead of which agent it runs, and every action says what it actually sends.',
    ],
    zh: [
      '长按卡片重做：不再在你看着它的时候反复重弹；标题换成会话在哪，而不是它跑的哪个 agent；每个动作都写明了它到底发出去什么。',
    ],
  },
  {
    version: '0.78.0',
    en: [
      'Long-press a session to act on it: answer its question, tell it to carry on or stop, or hand it to the supervisor.',
      'A session waiting on a permission prompt now shows as needing you, not as working.',
      'The terminal no longer stutters your typing while output arrives, and the jump-to-bottom arrow lands on the tail.',
    ],
    zh: [
      '长按一个会话就能动手：直接回答它的问题、让它继续或停下、或者交给参谋长。',
      '卡在权限提示上的会话现在显示成「需要你」，不再是「运行中」。',
      '终端刷新时打字不再卡顿，回到底部的箭头也真的落到底。',
    ],
  },
  {
    version: '0.77.0',
    en: [
      'The HQ page has a slimmer header, so the conversation finally has room.',
      'New: see what your supervisor did while you were away. Dispatches, clean-ups, the notes it kept.',
      'HQ\'s steps now show while it works, instead of folding away once it finishes.',
    ],
    zh: [
      'HQ 页头部瘦身，对话终于有地方了。',
      '新增：看得到参谋长替你做了什么。派活、回收、记的账都在这里。',
      'HQ 干活的过程边跑边看，不用等它跑完再去角落里翻。',
    ],
  },
  {
    version: '0.76.0',
    en: [
      'Fixed: a session\'s agent icon could turn into a plain two-letter mark and stay that way. One icon request failing on a weak connection was being treated as "this agent has no icon"; it now retries.',
    ],
    zh: [
      '修复：会话的 agent 图标有时会变成两个字母的字标，并且一直不恢复。以前只要有一次取图在弱网下失败，就被当成「这个 agent 没有图标」；现在会重试。',
    ],
  },
  {
    version: '0.74.0',
    en: [
      'Fixed: the lock-screen Live Activity counted gtmux\'s own supervisor as work in progress — it now counts only your sessions.',
      'Fixed: the lock-screen card could freeze hours behind — the app now keeps making sure this Mac can still push to it.',
      'Long-pressing a session now shows the full task and error, which pane it is, and one step to go look at it on the Mac.',
    ],
    zh: [
      '修复：锁屏实时活动把 gtmux 自己的中控算成了「工作中」，现在只统计你的会话。',
      '修复：锁屏卡片可能停在几小时前的状态不再更新 —— 现在会持续确保 Mac 能推送到它。',
      '长按一个会话现在给出完整任务与错误原文、它是哪个 pane，以及一步跳到 Mac 上去看。',
    ],
  },
  {
    version: '0.72.0',
    en: [
      'Fixed: the lock-screen Live Activity counted gtmux\'s own supervisor as work in progress — it now counts only your sessions.',
      'Fixed: the lock-screen card could freeze hours behind — the app now keeps making sure this Mac can still push to it.',
    ],
    zh: [
      '修复：锁屏实时活动把 gtmux 自己的中控算成了「工作中」，现在只统计你的会话。',
      '修复：锁屏卡片可能停在几小时前的状态不再更新 —— 现在会持续确保 Mac 能推送到它。',
    ],
  },
  {
    version: '0.67.0',
    en: [
      'Fixed: when an agent moved its conversation to a background process, the phone kept showing the old history.',
      'The chat now refreshes on its own instead of waiting for the pane\'s status to change.',
    ],
    zh: [
      '修复：agent 把对话搬到后台运行后，手机上的对话会停在旧记录不再更新。',
      '对话页现在自己会刷新，不用等状态变化。',
    ],
  },
  {
    version: '0.64.0',
    en: [
      'A session whose turn ended on a failure now has its own "errored" group, amber, right below the ones waiting for you — instead of sitting under a green tick among the finished ones.',
      'The situation board honours the line breaks the supervisor writes instead of printing the tag and running everything together, and struck-out items look struck out.',
      'Picking panes for a share link groups them by session and leads each row with its pane id; a link\'s summary counts only the panes it can still reach.',
    ],
    zh: [
      '停在错误上的会话现在有了自己的「出错」分区（琥珀色），紧挨在「需要你」下面 —— 而不是顶着绿勾躺在已完成里。',
      '态势板现在会遵守参谋长写的换行，而不是把标签原样打出来、把内容挤成一整段；划掉的条目也真的显示为划掉。',
      '给分享链接挑 pane 时按 session 分组、每行以 pane id 打头；链接摘要只数它还能到达的 pane。',
    ],
  },
  {
    version: '0.62.0',
    en: [
      'Version alignment with gtmux 0.62.0 — this release hardens the CLI/HQ side (loss-proof perception, a fully bilingual supervisor charter); no phone-side changes.',
    ],
    zh: [
      '与 gtmux 0.62.0 版本对齐 —— 本次加固都在 CLI/中控侧（不丢事件的感知、整份双语守则），手机端无功能变化。',
    ],
  },
  {
    version: '0.61.0',
    en: [
      'Version alignment with gtmux 0.61.0 — this release\'s improvements are on the CLI/HQ side (a supervisor that speaks to any user); no phone-side changes.',
    ],
    zh: [
      '与 gtmux 0.61.0 版本对齐 —— 本次改进都在 CLI/中控侧（面向任何用户的参谋长），手机端无功能变化。',
    ],
  },
  {
    version: '0.59.0',
    en: [
      'Picking panes for a share link now groups them by session and leads each row with its pane id, so two panes running the same project are no longer two identical-looking rows.',
      'A share link\'s summary counts the panes it can still reach and names the grants whose pane is gone; when tmux has restarted, the app says the links are being refused and how to restore them.',
      '"All panes" and Settings no longer overlap each other\'s tap areas.',
    ],
    zh: [
      '给分享链接挑 pane 时按 session 分组、每行以 pane id 打头 —— 两个跑着同一个项目的 pane，不再是两行长得一模一样、无从分辨的选项。',
      '分享链接的摘要只数它还能到达的 pane，并把已失效的授权明说出来；tmux 重启之后，app 会直说这些链接正被拒绝以及如何恢复。',
      '「所有 pane」和「设置」的点击区不再重叠。',
    ],
  },
  {
    version: '0.58.1',
    en: [
      '"All panes" and Settings no longer overlap each other\'s tap areas — aiming at the right half of "all panes" used to open Settings.',
      'A row marked "background running" names the actual command instead of a script\'s first line, which was often just a variable assignment.',
      'A share link\'s summary counts the panes it can still reach and names the grants whose pane is gone; when tmux has restarted, the app now says the links are being refused and how to restore them.',
    ],
    zh: [
      '「所有 pane」和「设置」的点击区不再重叠 —— 以前瞄准「所有 pane」右半边点，开的是设置。',
      '标着「后台运行中」的行现在显示真正的命令，而不是脚本的第一行（那往往只是个变量赋值）。',
      '分享链接的摘要只数它还能到达的 pane，并把已失效的授权明说出来；tmux 重启之后，app 会直说这些链接正被拒绝以及如何恢复。',
    ],
  },
  {
    version: '0.57.1',
    en: [
      'Paired devices now say what they ARE (iOS 26.6, Chrome 141 · macOS) and where they last connected from, and the list finally has an order — most recently seen first.',
      'A share link says whether anyone has used it, and from what device — or "not used yet", which is worth knowing about a link you handed out.',
    ],
    zh: [
      '配对设备现在会说出它是什么（iOS 26.6、Chrome 141 · macOS）和上次从哪连的，列表也终于有了顺序 —— 最近连接的排在前面。',
      '分享链接会说出有没有人用过、用的什么设备；没人用过就直说「还没有人用过」—— 对一份你发出去的链接来说，这是值得知道的。',
    ],
  },
  {
    version: '0.55.1',
    en: [
      'The all-panes browser draws the window line for every session now, including one that holds a single window, and a pane row sits indented inside its window instead of starting further left than the window line above it.',
      'A pane row no longer repeats the agent\'s name under its icon; the text says what the pane is doing.',
    ],
    zh: [
      '「所有 pane」浏览器现在每个 session 都画出窗口那一行（包括只有一个窗口的），pane 行也缩进在它所属的窗口里面，不再比上面那行窗口名还靠左。',
      'pane 行不再在图标下面重复 agent 名字，文字留给「这个 pane 在做什么」。',
    ],
  },
  {
    version: '0.55.0',
    en: [
      'The all-panes browser draws the window line for every session now, including one that holds a single window — the tree has the same shape everywhere instead of two shapes a row apart.',
      'A pane row no longer repeats the agent\'s name under its icon; the text says what the pane is doing.',
    ],
    zh: [
      '「所有 pane」浏览器现在每个 session 都画出窗口那一行，包括只有一个窗口的 —— 整棵树到处都是同一个形状，不再隔一行换一种。',
      'pane 行不再在图标下面重复 agent 名字，文字留给「这个 pane 在做什么」。',
    ],
  },
  {
    version: '0.54.0',
    en: [
      'The HQ situation board reads like a document again: wide tables stack into labelled blocks instead of running off the side of the screen, and inline code no longer leaves white marks through the prose.',
      'The board sheet stops repeating its own title, and says how long ago it was updated.',
    ],
    zh: [
      '中控态势板恢复成一份能读的文档：过宽的表格改为逐行堆叠并带上列名，不再从屏幕右侧跑掉；行内代码也不再在正文里留下一块块白斑。',
      '态势板页面不再把自己的标题重复一遍，改为直接告诉你它多久前更新过。',
    ],
  },
  {
    version: '0.53.0',
    en: [
      'The all-panes browser now shows the window level: panes are grouped under the window that holds them, and a session\'s header lists its windows even when folded.',
      'Every row leads with its pane id (%23) instead of a position that changes whenever panes are reordered. Tap the id to copy "gtmux focus %23".',
      'Search finds a pane by id too — %23, @17, or just the digits.',
    ],
    zh: [
      '「所有 pane」浏览器现在会显示窗口这一层：pane 按所属窗口分组，会话折叠起来时头部也会列出它有哪些窗口。',
      '每一行改为以 pane id（%23）开头，不再用会随重排而变的位置编号。点 id 即可复制 "gtmux focus %23"。',
      '搜索也能用 id 找 pane —— %23、@17，或直接敲数字。',
    ],
  },
  {
    version: '0.52.0',
    en: [
      'A notification\'s quick-reply buttons no longer claim a meaning they cannot know. They showed the same "1 · Yes / 2 · Always / 3 · No" whatever the agent was asking, so on a two-option prompt the button labelled Always sent the answer that means No. They now show only the number, the body lists the real options one per line, and there are exactly as many buttons as the agent offers.',
      'Long-pressing a notification shows the question instead of a giant coloured square.',
      'The HQ situation board reads as sections you can fold, and its headings are legible again instead of drowning in bold.',
    ],
    zh: [
      '通知的快回按钮不再声称它不知道的含义。以前不管 agent 在问什么，都显示同样的「1 · Yes / 2 · Always / 3 · No」——于是在两项提示上，标着 Always 的按钮发出去的答案其实是「No」。现在按钮只显示编号，正文一行一个列出真实选项，按钮个数与 agent 提供的一致。',
      '长按通知看到的是问题本身，而不是一大块彩色方块。',
      '中控态势板改成可折叠的分节，标题不再淹没在满屏加粗里。',
    ],
  },
  {
    version: '0.51.2',
    en: [
      'A session that is working now says so with a ring that turns, matching the Mac. It stays slow and calm — urgency is red, and red never moves. Reduce Motion is honoured.',
      'Rows no longer read "◐ my task name" when the agent on your Mac animates a spinner in its window title.',
    ],
    zh: [
      '正在工作的会话现在用一枚会转的环表示，与 Mac 端一致。转速很慢：着急是红色的事，而红色永不动。尊重系统的「减弱动态」。',
      '行里不会再出现「◐ 我的任务名」—— Mac 上的 agent 把转圈动画写在窗口标题里时，不会再漏到这里。',
    ],
  },
  {
    version: '0.51.1',
    en: [
      'The built-in demo now shows the same app the radar does: the all-panes browser, the fleet tally, and the waiting-only filter were missing from it.',
      'A few Chinese strings reworded.',
    ],
    zh: [
      '内置演示现在和真实雷达是同一个 app：之前它缺了「所有 pane」浏览器、舰队计数和「只看等输入」筛选。',
      '几处中文文案修订。',
    ],
  },
  {
    version: '0.50.0',
    en: [
      'The HQ page now speaks up about two things it used to stay quiet on: when the supervisor itself needs a decision from you, and when the Mac is genuinely short of disk, memory or power. It reported "all normal — nothing needs you" in both cases, while the Mac\'s own menu bar said otherwise about the very same fleet at the very same moment. That verdict is now decided once, on the Mac, and this app renders it — so the two can no longer disagree.',
    ],
    zh: [
      'HQ 页面现在会对两件它以前一声不吭的事开口：中控自己需要你拍板时，以及 Mac 真的磁盘、内存或电量吃紧时。这两种情况下它以前都显示「都正常 · 无需你介入」，而同一时刻、同一个舰队，Mac 上的菜单栏说的却是另一回事。这个判断现在由 Mac 端裁定一次，本 app 只负责呈现 —— 两边不会再各说各的。',
    ],
  },
  {
    version: '0.48.4',
    en: [
      'A link the terminal had to wrap onto a second line is one link again. A long URL used to be cut where the row ended, and only the first fragment was tappable — so it opened a host that did not exist while the real address sat below it as plain text. Every piece of a wrapped URL now opens the whole thing, including a URL the terminal recolours half-way through.',
      'Fewer false alarms in the radar: a session that merely SHOWS the words of a startup trust prompt — because you were reading or discussing them — is no longer reported as an agent stuck waiting for you, and a session that finishes while such text is on screen is no longer silently skipped. Needs gtmux 0.48.4 on the Mac.',
    ],
    zh: [
      '被终端折到第二行的链接，现在重新是一条完整链接。以前长 URL 会在行尾被切断，只有前半截可点 —— 于是点开的是一个并不存在的域名，而真正的地址就在下面躺着、还点不了。现在折行后的每一段都能打开完整地址，中途变色的 URL 也一样。',
      '雷达的误报变少了：屏幕上只是「出现」了启动信任提示的字样（你在读它、或者在讨论它），不再被报成有 agent 卡住等你；带着这类文字干完活的会话，也不会再被悄悄漏掉。需要 Mac 端升级到 gtmux 0.48.4。',
    ],
  },
  {
    version: '0.48.1',
    en: [
      'A conversation that looks empty now explains itself: a session started over with /clear or /new says which moment it starts from, and points at Activity for the record from before. A wiped supervisor history used to read as a broken app.',
      'The What\'s New card you are reading scrolls properly — it used to barely move — and now carries the gtmux mark and a single version chip instead of printing the version twice.',
      'Diff appears only where it can work: a pane sitting in a git repository offers it, and one outside a repository no longer shows a control that could only fail.',
      'Needs gtmux 0.48.1 on the Mac for the cleared-conversation notice; the rest works with what you have.',
    ],
    zh: [
      '看起来空白的会话现在会自己交代来龙去脉：以 /clear 或 /new 重新开始的会话会说明本轮从哪一刻起算，并指向「动态」查看更早的记录。以前中控的历史被清空，看上去就像 app 坏了。',
      '你正在读的这张「更新内容」卡片能正常滚动了 —— 以前几乎推不动 —— 并且带上了 gtmux 标识，版本号只显示一次，不再重复。',
      'Diff 只在能用的地方出现：位于 git 仓库里的 pane 才提供它，不在仓库里的 pane 不再显示一个注定失败的按钮。',
      '「会话已清空」这条提示需要 Mac 端升级到 gtmux 0.48.1；其余改动用现在的版本就能看到。',
    ],
  },
  {
    version: '0.47.0',
    en: [
      'What\'s new: after an update the app tells you what changed — every version you skipped, not just the latest. Read it again any time from Settings.',
      'Numbered lists in a reply are numbered again: 1, 2, 3 rather than 1, 1, 1. An item\'s wrapped text used to break the list apart.',
      'Landscape: the exit-full-screen button no longer covers the first line, content stays clear of the notch, and a phone keeps its single-column layout instead of borrowing the iPad\'s two-column one.',
      'With gtmux updated on the Mac: sending into a pane where you have unsent text is refused instead of swallowing it, a failed send can be retried straight away, and agents with no desktop app show their real icon.',
    ],
    zh: [
      '更新内容：升级后会告诉你改了什么 —— 你跳过的每个版本都会列出，而不只是最新那条。设置里随时可以再看一遍。',
      '回复里的有序列表重新会数数了：1、2、3，而不是 1、1、1。以前条目里换行的正文会把列表截断。',
      '横屏：退出全屏的按钮不再压住第一行；正文避开刘海；手机保持单栏布局，不再套用 iPad 的双栏。',
      '配合 Mac 端更新：往你有未提交内容的 pane 发消息会被拒绝，而不是把它吞掉；发送失败后可以直接重试；没有桌面 app 的 agent 也能显示真实图标。',
    ],
  },
  {
    version: '0.45.13',
    en: [
      'Native text selection in the terminal — long-press to select with the system handles and magnifier; Copy takes exactly what you selected.',
      'The terminal now renders as a true grid — typing and scrolling in a busy pane is much faster, and scrollback goes back 1,000 lines.',
      'Send now dismisses the keyboard, and the key row gains a backspace key.',
      'Fullscreen is a clean reading mode — the input bar gets out of the way.',
      'Polish: empty panes no longer show a black screen, multi-line input is no longer clipped, long diff lines scroll sideways, pane rows show the agent\'s name, and Snippets are now Quick replies.',
      'With gtmux updated on the Mac: typing into a plain (non-agent) pane no longer falsely reports a failure, and the Warp terminal is supported.',
    ],
    zh: [
      '终端支持原生文本选中：长按呼出系统选中手柄与放大镜，Copy 精确复制选中内容。',
      '终端改为真正的网格渲染：忙碌会话里打字、滚动明显更快，历史回看加深到 1000 行。',
      '发送后自动收起键盘；按键行新增退格键。',
      '全屏即纯阅读模式，输入条自动隐藏。',
      '打磨：空内容 pane 不再黑屏；多行输入不再被裁切；Diff 长行可横向滑动；pane 列表显示 agent 名称；「Snippets」更名「常用语」。',
      '配合 Mac 端更新：往普通终端 pane（非 agent 会话）输入不再误报失败；新增 Warp 终端支持。',
    ],
  },
];
